spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dor
    username: root
    password: 184520
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml